server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Gateway, API-Gateway
      discovery:
        locator:
          enabled: false
      routes:
        - id: git-diff-service
          uri: http://git-diff-service:8080
          predicates:
            - Path=/diff/**
          filters:
            - StripPrefix=1

        - id: ssh-sync-service
          uri: http://ssh-sync-service:8080
          predicates:
            - Path=/sync/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
  prometheus:
    enabled: true

jwt:
  secret: ${JWT_SECRET}

security:
  permitted-paths:
    - /actuator/**
    - /git/actuator/**
    - /ssh/actuator/**
