server:
  port: ${SSH_SYNC_SERVER_PORT:8082}
  address: ${SSH_SYNC_ADDRESS:127.0.0.2}
spring:
  application:
    name: ssh-sync-service

ssh:
  port: 22
  timeout-ms: 15000
  strict-host-key-checking: false
  preferred-authentications: publickey,password,keyboard-interactive