server:
  port: ${SSH_SYNC_SERVER_PORT:8082}
  address: ${SSH_SYNC_SERVER_ADDRESS:127.0.0.2}
  tomcat:
    connection-timeout: 120s

spring:
  application:
    name: ssh-sync-service
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

ssh-sync:
  port: 22
  timeout-ms: 15000
  scp-buffer-size: 16384
  ack-wait-iterations: 100
  ack-wait-interval-ms: 10
  strict-host-key-checking: false
  preferred-authentications: password,publickey,keyboard-interactive

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
  prometheus:
    enabled: true

