apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus                      # будем ссылаться на этот uid из дашборда
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
