global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'git-diff-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'git-diff-service:8080' ]

  - job_name: 'ssh-sync-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'ssh-sync-service:8080' ]

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8080' ]
