server:
  port: 9090
  shutdown: graceful

marketplace:
  base-url: "https://plugins.jetbrains.com"
  request-timeout: 5s
  cache-ttl: 15m
  user-agent: "RemoteSync/1.0 (+JetBrains Plugin Stats)"

spring:
  main:
    web-application-type: reactive
